# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

hostname: "bffcd449.ngrok.io" # MESSENGER_HOST

applicationID: "1977610539125363" # MESSENGER_APP_ID
accessToken: "EAAcGoFWwSnMBAKBjPm1EcXH7VEtjsYWCIxjoaILRrh54P2XGz37Y1dImmoxIshloMKOqyeb27D5IaWgnZCQ9nO1Ms8ZCVsH1jTmNkpZBEm2ZB36P5fdkVBtPbWrxo21F90uaCStYKxjHFTTmx2t4VPjAPhZClZCnJ0m5N0eZACFJKVGYRqq2mZBQ" # MESSENGER_ACCESS_TOKEN
appSecret: "44785adde996f466e3408fb2401922ac" # MESSENGER_APP_SECRET

verifyToken: "secret" # MESSENGER_VERIFY_TOKEN

displayGetStarted: true
greetingMessage: ""

# https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu
# persistentMenuItems: []

targetAudience: openToAll
# targetAudienceOpenToSome: ""
# targetAudienceCloseToSome: ""

# trustedDomains: []
# autoRespondGetStarted: true

# paymentTesters: []

# chatExtensionHomeUrl: ""
# chatExtensionInTest: true
# chatExtensionShowShareButton: false

enabled: true